### ISSUE TITLE
Website pdf.math.dev doesn't work

### ISSUE THREAD

**Issue by mkilinskidev** [ashok-khanna/pdf#4]
In the console we can find some issues
```
Uncaught (in promise) DOMException: Failed to execute 'querySelectorAll' on 'DocumentFragment': '</pre></code>
<h3>Page Breaks</h3>
<p>By default' is not a valid selector.
    at Breaks.processBreaks (https://pdf.math.dev/paged.polyfill.js:28816:27)
    at Breaks.afterParsed (https://pdf.math.dev/paged.polyfill.js:28810:9)
    at https://pdf.math.dev/paged.polyfill.js:364:26
    at Array.forEach (<anonymous>)
    at Hook.trigger (https://pdf.math.dev/paged.polyfill.js:363:15)
    at Chunker.flow (https://pdf.math.dev/paged.polyfill.js:2583:33)
    at async Previewer.preview (https://pdf.math.dev/paged.polyfill.js:31035:15)
    at async https://pdf.math.dev/paged.polyfill.js:31096:11
```

**Comment by ashok-khanna** [comment]
Can you let me know your browser / operating system etc? I will have a look. It works best on Chrome and I tested on MacOS and if I remember correctly Windows. The main use is as part of a headless chrome setup to automate pdf generation from HTML files, but I will have a look anyway when I have some time. Thanks for raising it.

**Comment by mkilinskidev** [comment]
Windows 10 19043.1023, Microsoft Edge 91.0.864.41
